name = "Euclid"
version = "0.1.0"
defaultTargets = ["Euclid"]

[[lean_lib]]
name = "Euclid"

[[lean_lib]]
name = "Sharygin11Problem4"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin11Problem5"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin11Problem1"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin11Problem3"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin11Problem6"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin12Problem7"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin12Problem8"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin12Problem10"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin12Problem9"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin12Problem11"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin12Problem12"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin13Problem13"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin13Problem14"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin13Problem15"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin13Problem16"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin14Problem18"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin14Problem21"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin14Problem22"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin14Problem23"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin15Problem24"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin15Problem25"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin15Problem26"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin15Problem27"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin15Problem28"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin15Problem29"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin15Problem30"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin16Problem31"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin16Problem32"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin16Problem33"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin16Problem34"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin16Problem35"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin16Problem36"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin16Problem37"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin16Problem38"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin17Problem39"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin17Problem40"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin17Problem41"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin17Problem42"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin17Problem43"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin17Problem44"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin17Problem45"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin18Problem46"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin18Problem47"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin18Problem48"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin18Problem49"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin18Problem50"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin19Problem51"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin19Problem52"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin19Problem53"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin19Problem54"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin19Problem55"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin19Problem56"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin20Problem57"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin20Problem58"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin20Problem59"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin20Problem60"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin20Problem61"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin20Problem62"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin20Problem63"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin21Problem65"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin21Problem66"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin21Problem67"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin21Problem68"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin21Problem69"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin22Problem70"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin22Problem71"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin22Problem72"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin22Problem73"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin22Problem74"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin22Problem75"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin22Problem76"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin23Problem77"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin23Problem78"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin23Problem79"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin23Problem80"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin23Problem81"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin23Problem82"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin24Problem83"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin24Problem84"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin24Problem85"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin24Problem86"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin24Problem87"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin25Problem88"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin25Problem89"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin25Problem90"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin25Problem91"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin25Problem92"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin25Problem93"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin26Problem94"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin26Problem95"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin26Problem96"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin26Problem97"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin26Problem98"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin14Problem20"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin13Problem17"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin14Problem19"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin11Problem2"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin73Problem27"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin74Problem28"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin74Problem29"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin74Problem30"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin74Problem31"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin74Problem32"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin75Problem33"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin75Problem34"
srcDir = "soultions"

[[lean_lib]]
name = "Sharygin75Problem35"
srcDir = "soultions"
